### ISSUE TITLE
Use of WeakHashMap in com.twitter.scalding.RuntimeStats has made usage of scalding Stats unreliable

### ISSUE THREAD

**Issue by vineethvarghese** [twitter/scalding#1182]
While using the Scalding Stats, we often encounter the following stacktrace :-
```
Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(1490058012982771712) isn't available
    at scala.sys.package$.error(package.scala:27)
    at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
    at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
    at scala.Option.getOrElse(Option.scala:120)
    at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
    at com.twitter.scalding.Stat$$anon$1.flowProcess$lzycompute(Stats.scala:50)
    at com.twitter.scalding.Stat$$anon$1.flowProcess(Stats.scala:50)
    at com.twitter.scalding.Stat$$anon$1.incBy(Stats.scala:52)
    at com.twitter.scalding.Stat$class.inc(Stats.scala:30)
    at com.twitter.scalding.Stat$$anon$1.inc(Stats.scala:48)
    at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
    at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
```
Upon further test, we found that the use of a WeakHashMap was the root cause of the problem. The keys don't seem to hang around for too long (after all they are weakly referenced). If I change the RuntimeStats code to maintain a strong reference to these keys, the Stats seem to work as expected.

The obvious question is how should we use the Stats feature if the underlying mechanism is based on a weakly referenced object. I didn't find any issues filed against scalding for this so I am a bit curious as to why we are facing this.

**Comment by ianoc** [comment]
I'm not sure why you are facing this really. We haven't ran into it
internally, without weak it will keep flow processes around after they
should be removed. How do you launch/run your jobs ?

**Comment by vineethvarghese** [comment]
Basically, we bundle a fat jar and run it via hadoop -jar. 

We were tracking this issue https://github.com/CommBank/maestro/issues/300

A simple pointer to a test where I could replicate this is https://gist.github.com/vineethvarghese/357334a5fbd4ff16907e

The code where the stat is used is :- 
```
def process(in: TypedPipe[RawRow], stat: Option[Stat]) = 
    in.map (row => row.line.split("\\|").map(_.trim))
      .flatMap { elements => {
        if (elements.headOption.exists(_ == "D")) {
          Some(elements.tail) 
        } else {
          stat.foreach(_.inc)
          None
        }
      }
    }
```
Here I am trying to count and filter out rows that doesn't start with "D". As long as these rows come at the beginning of the file, we are good. But if these rows are at the end of a file, I run into this issue.

**Comment by ianoc** [comment]
Your using a cascading operation in that example, the registration of the flow process is done in the operation prepare in scalding. Not really sure but it seems the most unusual compared to our normal operation. The map in question goes from a String -> WeakReference[FlowProcess] @ https://github.com/twitter/scalding/blob/2d8aa06ddae0ce2e86d6f5c170a53ea6e5f197c8/scalding-core/src/main/scala/com/twitter/scalding/Stats.scala#L111

The flow process registered shouldn't be able to be GC'd while your still running, so the only other thing is somehow it's never getting registered. You could try inject a few println's in a custom build around the registration/lookups to see if the registration isn't occuring? (Also when querying for the String, dump the entire map encase the ID isn't right possibly).

**Comment by vineethvarghese** [comment]
I will try that but I replaced the WeakHashMap with a HashMap and don't see this issue.

**Comment by ianoc** [comment]
Ok, well that suggests the registration code is being hit, but why is your flow process got no references from anywhere else? (It should be only reason a WeakReference gets collected...).

**Comment by vineethvarghese** [comment]
The flow process is the value of the map (wrapped in a WeakReference) but the issue I see is the keys of the map being cleared. I broke out the for comprehension to see what was being GCed as below :-
```
def getFlowProcessForUniqueId(uniqueId: UniqueID): FlowProcess[_] = {
    val fpRefOption = flowMappingStore.get(uniqueId.get)
    if (fpRefOption.isEmpty) {
      sys.error("FlowProcess for unique id %s is gone".format(uniqueId))
    }
    val fpRef = fpRefOption.get
    val fpOption = fpRef.get
    if (fpOption.isEmpty) {
      sys.error("FlowProcess instance in map  is empty")
    }
    fpOption.get
    // (for {
    //   weakFlowProcess <- flowMappingStore.get(uniqueId.get)
    //   flowProcess <- weakFlowProcess.get
    // } yield {
    //   flowProcess
    // }).getOrElse {
    //   sys.error("Error in job deployment, the FlowProcess for unique id %s isn't available".format(uniqueId))
    // }
  }
``` 
and hit "FlowProcess for unique id %s is gone"

**Comment by ianoc** [comment]
Ah, yes, so the bug here is this:

Originally the code in addFlowProcess added a string from the flowProcessMap, which i guess if the values were kept deserialized would have made that a strong reference from inside the flowProcess. The newer code however splits that string based on comma's, so the strings generated are transient and not rooted. Neither case seems maybe totally ideal to rely on.

One thing we could do is that we make it a strong map, but on adding a unique ID we scan the map for dead weakreferences pruning those elements. In a testing/long running setting that should hopefully avoid heap problems (why all these weak references are unfortunately here), or a long running execution dispatching setting also. 

thoughts @johnynek ?

**Comment by vineethvarghese** [comment]
@ianoc I am probably wrong here but with the RuntimeStats.addFlowProcess method :- 
```
def addFlowProcess(fp: FlowProcess[_]) {
    val uniqueJobIdObj = fp.getProperty(UniqueID.UNIQUE_JOB_ID)
    if (uniqueJobIdObj != null) {
      uniqueJobIdObj.asInstanceOf[String].split(",").foreach { uniqueId =>
        logger.debug("Adding flow process id: " + uniqueId)
        flowMappingStore.put(uniqueId, new WeakReference(fp))
        //flowMappingKeys += uniqueId
      }
    }
  }
```
what is stopping "uniqueId" from being garbage collected?

**Comment by vineethvarghese** [comment]
Ignore my previous comment :)

**Comment by isnotinvain** [comment]
If the problem is weak keys (and the keys are strings) getting GCed, then instead of using both weak keys + weak values we can go with what I originally mentioned in #829 and keep the keys (which are just strings) as strong references.

This should be OK -- one problem we've seen is that *values* contain a reference to their key so strong *values* inherently cause strong keys, but that's not the case here.

**Comment by isnotinvain** [comment]
Seems like the flow process is the expensive part, so keeping some strings as keys shouldn't be too bad right? As @ianoc said we could even do read-repair of some kind to drop keys for GCed values.

**Comment by avibryant** [comment]
Just FWIW - this matches our experience with `Stats` (I've stopped using them because of intermittent but frequent issues, but hadn't done the work to track down the problem). So thanks @vineethvarghese!

**Comment by johnynek** [comment]
@ianoc frankly, I think just making the change @vineethvarghese suggests is fine. These maps are built up on the tasks, and those tasks run a finite period of time. So, at least in hadoop mode, this should never be an issue. In local mode, it could be an issue, but only if you have a large and growing number of UniqueIDs. If you use Execution properly, you would use only one UnqueID for the entire computation, even if it loops.

So, at the end of the day, I don't see much danger in the simple fix.

By the same token, if you did the scan, that would be fine too since the map is expected to be so small that we should not see any issue scanning it.

**Comment by ianoc** [comment]
Ok, perfect. Based on all this would love a PR that just makes it a HashMap rather than the weak one. If there is no real risk from executions it would only be a problem in the extreme case of a test suite running long enough to fill the JVM with strings. Extra code required to do cleanup doesn't seem worth it to cover this case.

**Comment by rubanm** [comment]
This could be made a little more flexible using SoftReferences? But seems like we're better off using strong references if we want correctness.

**Comment by wbertelsen** [comment]
I've started to encounter the `Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(...) isn't available` issue in hadoop mode with code I know is running against 0.13.1 (confirmed in the jobtracker). 

The exception happens on my reducers - I think it happens immediately after shuffle on the first attempt to increment a stat, but I don't quite have enough logs to be sure of that. 

The only code change I have between the job that works and the job that always fails affects an earlier step of my job (though it increases the input size to the reducers where the failure occurs). 

Tomorrow I'll try to test my job against a version of scalding that use SoftReferences and one that uses strong refs to be sure it's a GC issue, but I figured I'd update this issue first. 

If GC is still the issue I'm tempted to agree with @rubanm strong references (plus code to manually clean up the map?) are preferable to rolling the dice on the garbage collector.

**Comment by johnynek** [comment]
This was inside of a join. For Joins, I think we are not setting the
FlowProcess (that is a whole in our implementation), because we don't use
any Cascading operation at that point: we are doing all the logic in a
cascading Joiner (to make them compose well).

Let's see if we can get access to the FlowProcess in a Joiner.

On Fri, Mar 27, 2015 at 4:51 AM, Will Bertelsen <notifications@github.com>
wrote:

> Here is an abbreviated stack
>
> java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(455973893) isn't available
>   at scala.sys.package$.error(package.scala:27)
>   at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
>   at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
>   at scala.Option.getOrElse(Option.scala:120)
>   at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
>   ... 4sq code
>   at com.twitter.scalding.typed.Grouped$$anonfun$addEmptyGuard$1.apply(Grouped.scala:90)
>   at com.twitter.scalding.typed.Grouped$$anonfun$addEmptyGuard$1.apply(Grouped.scala:90)
>   at com.twitter.scalding.typed.CoGrouped$$anon$6$$anonfun$joinFunction$2.apply(CoGrouped.scala:182)
>   at com.twitter.scalding.typed.CoGrouped$$anon$6$$anonfun$joinFunction$2.apply(CoGrouped.scala:174)
>   at com.twitter.scalding.typed.CoGroupedJoiner.getIterator(CoGrouped.scala:303)
>   at cascading.flow.hadoop.stream.HadoopGroupGate.run(HadoopGroupGate.java:88)
>   at cascading.flow.hadoop.FlowReducer.reduce(FlowReducer.java:136)
>   at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:506)
>   at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:447)
>   at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at javax.security.auth.Subject.doAs(Subject.java:415)
>   at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
>   at org.apache.hadoop.mapred.Child.main(Child.java:262)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1182#issuecomment-86962862>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by tdyas** [comment]
Will and I talked a bit about this issue last night. I dug in and found the `FlowProcess` is available in custom joiners via calling `closure.getFlowProcess()` in an implementation of the `getIterator` method of `cascading.pipe.joiner.Joiner`. Since Scalding also uses `Joiner` classes built into Cascading, Scalding should probably wrap them with a proxy that stores the `FlowProcess` and then delegates to the wrapped `Joiner`. (Any custom subclass of `Joiner` in Scalding will need to also store the `FlowProcess`.)

**Comment by tdyas** [comment]
Rough draft of a fix: https://github.com/twitter/scalding/pull/1235
