### ISSUE TITLE
Add rollup macro

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1420]
See: https://gist.github.com/johnynek/dfa319c55934b8a38524

something like:

```scala
trait TypedPipe[T] {
  def rollup[K, V](implicit roller: Roller[K], ev: T <:< (K, V)): Grouped[roller.K, V] =
    raiseTo[(K, V)].flatMap { case (k, v) => roller(k).map((_, v)) }.group.sum
}

trait Roller[I] {
  type K
  def apply(in: I): TraversableOnce[K]
}
// we have macros to generate these so you get t => List(Some(t), None), and the cross product of that
// for case classes and tuples: (Int, String) => Seq[(Option[Int], Option[String])]
```

**Comment by ianoc** [comment]
I presume you mean need instead of have in the comment right ?

**Comment by johnynek** [comment]
Yes. :smiley: Something like "then we have macros do this hard work" rather than "we now have macros..."

**Comment by sid-kap** [comment]
(This is more of a general question about the organization of the Grouped and CoGrouped traits.)
Why put this in TypedPipe instead of Grouped[K,V]? I thought you can only rollup after grouping?

**Comment by ianoc** [comment]
Most of people's code spends its time in the TypedPipe type rather than Grouped would one one reason. 

But in this case you couldn't do that. Once your in grouped the type of the key is fixed, in order to be able to cube you need to take a type K the user intended and turn it into a type P instead where its got the nullable aspects.

e.g.

(String, Long) -> (Option[String], Option[Long])

**Comment by sid-kap** [comment]
Okay I see. So we need the implicit conversion `Grouped[K, V] -> TypedPipe[(K, V)]` because `Grouped[K, V]` doesn't have the flatMap method that we need.

The danger here is that people might be able to shoot themselves in the foot by calling `rollup` on their TypedPipe, forgetting to group (if they happen to have T=Tuple2, I suppose).

Maybe we should put rollup in Grouped and call the conversion to TypedPipe ourselves, something like
```scala
trait Grouped[K, V] {
  def rollup[K, V](implicit roller: Roller[K]): Grouped[roller.K, V] =
    toTypedPipe.doStuff...
}
```

**Comment by ianoc** [comment]
we have an implicit conversion from Grouped to TypedPipe now.

But the roller function can only be defined on typed pipes, you could have 2 versions if you really want something on grouped, something to initially change the type, and then an expander. But our functions on grouped don't let you change the key usually, since that itself breaks a bunch of contracts. (i.e. once you do any operation on a grouped we could be in the reducer often which means your keys must be fixed, since you sorted on them).

You should only be calling rollup on a typed pipe, and it should return a grouped

The scala collections version of what you want to do would be something like:
val res: Map[(Option[String], Option[Int]), Int] =  List((("abcd", 234), 123), (("def", 837), 562)).rollup

Taking that in terms of Scalding you end up with the function being on the typed pipe. You could indeed return a typed pipe again, but you can possibly compose more things by returning a grouped.

**Comment by johnynek** [comment]
Good point. You could probably put that `Roller` type in algebird so we
could use it on standard collections and with spark.

On Thu, Aug 13, 2015 at 3:03 PM, ianoc <notifications@github.com> wrote:

> we have an implicit conversion from Grouped to TypedPipe now.
>
> But the roller function can only be defined on typed pipes, you could have
> 2 versions if you really want something on grouped, something to initially
> change the type, and then an expander. But our functions on grouped don't
> let you change the key usually, since that itself breaks a bunch of
> contracts. (i.e. once you do any operation on a grouped we could be in the
> reducer often which means your keys must be fixed, since you sorted on
> them).
>
> You should only be calling rollup on a typed pipe, and it should return a
> grouped
>
> The scala collections version of what you want to do would be something
> like:
> val res: Map[(Option[String], Option[Int]), Int] = List((("abcd", 234),
> 123), (("def", 837), 562)).rollup
>
> Taking that in terms of Scalding you end up with the function being on the
> typed pipe. You could indeed return a typed pipe again, but you can
> possibly compose more things by returning a grouped.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1420#issuecomment-130861641>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by johnynek** [comment]
I'd love to get this into the next release of scalding. We'd need to make a PR after the next algebird is published.

**Comment by ianoc** [comment]
Seems like a reasonable plan, we have the updates to QTree in Algebird too that are also worth releasing. I'll do an OSS release of algebird when I can get a chance, which will unlock being able to get the PR in here
