### ISSUE TITLE
Scalding Execution API memory leak / OOM

### ISSUE THREAD

**Issue by vineethvarghese** [twitter/scalding#1459]
We are running into OOM issues due to https://github.com/twitter/scalding/pull/1057

We have some `Execution` jobs that takes an hour or more to run and lift some heavy lists through the `Execution` monad assuming gc will take care after we are done using them. However, we see that all the object we raise through `Execution` are held in the cache well after their use.

I have created a test case for this which you can find at https://github.com/CommBank/execution-memory. Details of how to run the test is in the README and you don't need Hadoop for it. While the example might seem a tad aggressive in its object creation, it is pretty much a dumbed down version of our job.

**Comment by johnynek** [comment]
Execution.run definitely is currently biased now to absolutely minimize work at the expense of memory. It is probably not a good general IO monad for that reason, even though it might look sort of like that.

We could address this at least two three ways:

1. disable all caching. I think this is a non-starter because it can result in hadoop jobs being run over and over again needlessly (and sadly, not all hadoop jobs are idempotent).

2. we could only cache infinitely hadoop writes: https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Execution.scala#L226 but we could use a weak or soft reference on the general cache: https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Execution.scala#L224

3. We could only cache the writes, but not cache at all the non-writes, so `Execution.fromFuture` which is ultimately how `Execution.from` is implemented, would not be cached.

What are your thoughts?

**Comment by johnynek** [comment]
@vineethvarghese Also I note you are using a very old version of scalding in the test. If we fix it, are you going to be able to consume it?

**Comment by johnynek** [comment]
Also, could you use another monad and then lift it into Execution as a work around? For instance you could use something like scalaz's Task? You could write the code that is creating millions of operations inside of a scalaz.Task, and then write a method `def liftTask[T](t: Task[T]): Execution[T]` which would `unsafePerformSync` inside `Execution.fromFuture { implicit cec => Future(task.unsafePerformSync) }`.

Might be a work-around until we get the trade-offs correctly here.

**Comment by vineethvarghese** [comment]
@johnynek Thanks for your quick response. Let me try to answer your questions here.

We were thinking along the lines of item 2. Item 1 is definitely a no. Item 3 also won't work if you look at the code below. 

We are ok to upgrade to the latest version. 

We do have our own monad that we use most of the time and could lift the values to Execution as late as possible. However, this won't really address our problem because our code looks something like :- 

```scala
for {
  p1s <- Hdfs.getPaths 
  _   <- TypedPipe.writeExecution
  p2s <- Hdfs.getPaths
}

```
where `Hdfs` is a monad but it sandwich an `Execution` with the write. So, it quickly gets messy.

**Comment by rowandavies** [comment]
@vineethvarghese Actually, I think 3 could help resolve the issue (and our issue more generally).  Although, I guess it would be breaking change there's code that relies on the effects not being repeated.  Perhaps adding a separate non-caching version of Execution.from would be bettter?

**Comment by vineethvarghese** [comment]
@rowandavies Yes it does work but it requires the API user to worry about these problems while coding. In our case, we are probably ok but from an API point of view I am not sure.

**Comment by johnynek** [comment]
@rowandavies also, we have access to the Config when we start evaluating the Execution, we could have an option to only cache hadoop operations. This would re-evaluate `Execution.fromFuture` and maps/flatMaps etc... but only run each WriteExecution once.

Would this work for you?

**Comment by rowandavies** [comment]
@vineethvarghese @johnynek Sure, I agree that requiring something like `Execution.fromNonCaching` every time a large data structure is yielded is awkward and may often be forgotten by mistake.  Having an option in the Config would be better, and would still be non-breaking.

Doing some tests, it seems that there aren't that many common cases where two apparently equivalent `Execution` instances have `execution1 == execution2` being true to allow a hit in the `EvalCache`.  E.g.:

 ```scala
    Execution.from(3) == Execution.from(3)     // is false
```

So, I think each call to `from` yields an `Execution` equal only to itself.  Thus, 

Similarly:

```scala
    x.flatMap(_ => y) == x.flatMap(_ => y)      // is false  (for any Executions `x` and `y`)
```

Thus (excluding unusual situations like where `equal` is overridden in a subclass of `Function1`) I think calls to `flatMap` lead to equal `Execution`s only when the function object is explicitly a reference to the same function object like in the following:  

```scala
      val f = (u: Int) => y         //  (Note:  using `def f(u: Int) = y` leads to false below instead)
      x.flatMap(f) == x.flatMap(f)   // is true
```

**Comment by rowandavies** [comment]
(Continuing since I submitted the previous by accident.)
Anyway, my point is that having the Config option to cache only hadoop operations seems reasonable, and since there are likely few cache hits otherwise, it may even make sense to make this the default at some point.

I'd agree that `Execution` shouldn't aim to be a general IO monad, it has a specific purpose, but it would be nice if it composed well so it could be used as part of the definition of other monads that include other aspects and effects also.  I think caching every value yielded goes against that based on the experiments we've done so far with such things.  In particular, this tends to involve using `Execution.from` to "pass through" results when only effects from other monadic aspects are involved, and having this always lead to non-garbage collected objects is rather limiting and awkward.

**Comment by rowandavies** [comment]
Putting the last part another way: `Execution` shouldn't aim to be a general IO monad, but it should aim to fully satisfy the monad laws to support composability and avoid surprising differences between similar code.  And with the current implementation of the pure injection `ExecutionMonad.apply(t)` as `Execution.from(t)` as per [Execution.scala#L197](https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Execution.scala#L197), the monad law 

```scala
      flatMap(apply(x))(fn) == fn(x)           
```

doesn't fully hold if we care about space leaks and memory safety, since `flatMap(apply(x))(fn)` has the extra "effect" of preventing future garbage collection of `x`, which doesn't happen with `fn(x)`.  I'd argue that to prevent "surprising differences" implementations of monads should aim to have the monad laws preserve memory safety where possible (but I've certainly seen many other monad implementations where they don't).

**Comment by vineethvarghese** [comment]
@johnynek @rowandavies Sorry for the delay in responding as I had to take a break. 

The current PR could be problematic in the sense that it could have surprising effects or inconsistencies. Unless there is a really good reason(which I can't see at the moment), I think the config option is a good way to approach this issue.

**Comment by rowandavies** [comment]
Just to update this, https://github.com/CommBank/maestro/pull/478 https://github.com/CommBank/maestro/commit/c18183d74ce9f2d978e8fcce9b44ec9ce2593d6f
adds `RichExecution.withSeparateCache` which a workaround via `run` to wrap an `Execution` so it runs separately, hence with the cache gc'ed.  

This works, and resolves the main memory leak and OOM issues we experienced, but using `run` is clearly a departure from good monadic style.  I think it would be better to implement something like this within `Execution`, and/or make `Execution.from` non-caching - I'd gladly create a PR with these.

**Comment by johnynek** [comment]
This is a good solution to me: creates a sub cache. Ugly to have to think about it, but also it is painful to go back on the exactly once contract now.

So, I'd welcome a PR to add that a `withNewCache` or something as long as the docs were clear (only use this when tuning OOM issues around Execution caching, or something).
